version: '3.7'

services:
  app_tests:
    container_name: app_tests
    image: python:3.10-slim
    volumes:
      - .:/tests/
    working_dir: /tests/
    command:
      bash -c "pip install -r MenuApp/requirements.txt && cd MenuApp && alembic upgrade head && cd .. && pytest Test_MenuApp/test_app/ -v"
    depends_on:
      - postgresql
    restart:
      always
    ports:
      - 8001:8001
    networks:
      - tests_db_network


  postgresql_tests:
      container_name: postgresql_tests
      image: postgres:15.1-alpine
      environment:
#        POSTGRES_DB: "postgres"
#        POSTGRES_USER: "postgres"
#        POSTGRES_PASSWORD: "postgres"
        POSTGRES_INITDB_ARGS: "-A md5"
      env_file:
        Test_MenuApp/.env
      restart:
        always
      expose:
        - 5432
      networks:
        - tests_db_network
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -d $${DB_NAME} -U $${DB_USER}" ]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s

networks:
  tests_db_network:
    driver: bridge
