version: '3.7'

services:
  app:
    container_name: app
    image: python:3.10-slim
    volumes:
      - .:/app/
    working_dir: /app/
    command:
      bash -c "pip install -r MenuApp/requirements.txt && cd MenuApp && alembic upgrade head && cd .. && pytest Test_MenuApp/test_app/ -v"
    depends_on:
      postgres_tests:
        condition: service_healthy
    env_file:
      Test_MenuApp/.env
    networks:
      - test_db_network

  postgres_tests:
      container_name: postgres_tests
      image: postgres:15.1-alpine
      env_file:
        Test_MenuApp/.env
      restart: on-failure
      ports:
        - 5433:5432
      expose:
        - 5432
      networks:
        - test_db_network
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready $${POSTGRES_DB} -U $${POSTGRES_USER}"]
        interval: 5s
        timeout: 10s
        retries: 5

networks:
  test_db_network:
    driver: bridge
