version: '3.7'

services:
  app:
    container_name: app
    image: python:3.10-slim
    volumes:
      - ./MenuApp:/app/MenuApp
    working_dir: /app/MenuApp
    env_file:
      MenuApp/.env
    command:
      bash -c "pip install -r requirements.txt && alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_db_network

  postgres:
      container_name: postgres
      image: postgres:15.1-alpine
      env_file:
        MenuApp/.env
      restart: on-failure
      expose:
        - 5433
      networks:
        - app_db_network
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h $${URL_DB} -p $${DB_PORT}"]
        interval: 5s
        timeout: 10s
        retries: 5

networks:
  app_db_network:
    driver: bridge
