version: "3.7"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      MenuApp/.env
    volumes:
      - app_data:/app/reports
    command:
      bash -c "cd MenuApp && alembic upgrade head && cd .. &&
      uvicorn MenuApp.src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    networks:
      - app_db_network

  postgres:
      container_name: postgres
      image: postgres:15.1-alpine
      env_file:
        MenuApp/.env
      restart: on-failure
      ports:
        - 5433:5432
      networks:
        - app_db_network
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h $${URL_DB} -p $${DB_PORT}"]
        interval: 10s
        timeout: 10s
        retries: 5

  redis:
    container_name: redis
    image: redis:latest
    restart: on-failure
    command: redis-server
    ports:
      - 6380:6379
    networks:
      - app_db_network
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5

  rabbit:
    image: rabbitmq:3.11.8-management
#    restart: always
    env_file: MenuApp/.env
    hostname: rabbitmq
    volumes:
      - app_data:/app/reports
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - app_db_network
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    container_name: celery
    build: .
    volumes:
      - app_data:/app/reports
    env_file:
      - MenuApp/.env
    networks:
      - app_db_network
    command: "celery -A MenuApp.src.services.tasks.cel:celery worker --loglevel=INFO"
    depends_on:
      redis:
        condition: service_healthy
      rabbit:
        condition: service_healthy
      app:
        condition: service_started

networks:
  app_db_network:
    driver: bridge

volumes:
  app_data:
