version: "3.7"

services:
  app:
    container_name: app
#    image: python:3.10-slim
#    volumes:
#      - ./MenuApp:/app/MenuApp
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/MenuApp
    env_file:
      MenuApp/.env
    command:
      bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_db_network

  postgres:
      container_name: postgres
      image: postgres:15.1-alpine
      env_file:
        MenuApp/.env
      restart: on-failure
      ports:
        - 5433:5432
      networks:
        - app_db_network
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h $${URL_DB} -p $${DB_PORT}"]
        interval: 10s
        timeout: 10s
        retries: 5

  redis:
    container_name: redis
    image: redis:latest
    restart: on-failure
    command: redis-server
    ports:
      - 6380:6379
    networks:
      - app_db_network
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  app_db_network:
    driver: bridge
